In [1]:
# Sort the DataFrame in ascending order with respect to the marks in Science.
# Sort the DataFrame in descending order with respect to the marks in Hindi.
# Show the DataFrame of only those students who scored more than 50 marks in all subjects.
# Show the list of students who got less than 40 marks in at least one subject.
# Show the list of students who scored the highest marks in each subject.
# Filter out the students who scored more than 90 marks in Science, and sort them in descending order with respect to their total marks.
# Show the names of the students who scored between 60 and 70 in Math.
# Show the list of students who have the highest marks in English and arrange them in ascending order based on their Hindi marks.
# Create a new column called 'Grade' where students with total marks greater than 400 get 'A', between 300-400 get 'B', and below 300 get 'C'.
# Show the details of students whose total marks are in the top 10%.
# Show the details of students who scored exactly 50 in any subject.
# Show the DataFrame where students' marks in Science and Hindi are sorted in ascending order, while keeping all other columns unchanged.
# Show the list of students who scored more than 85 marks in any three subjects.
# Create a DataFrame of students who have failed in two or more subjects.
# Rank the students in descending order of total marks, and assign ranks such that no two students share the same rank.
# Show the details of students whose marks are an exact multiple of 5 in all subjects.
# Show the average marks obtained in each subject by the entire class.
# Display the count of students who scored more than 70 in each subject.
# Show the details of students who scored the same marks in Math and Science.
# Filter out the students who scored the highest in Math, but less than 50 in English.

In [2]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generating Indian student names
student_names = [
    'Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun',
    'Sai', 'Reyansh', 'Ayaan', 'Anaya', 'Naira',
    'Saanvi', 'Ishaan', 'Riya', 'Kaira', 'Krishna',
    'Dhruv', 'Lakshmi', 'Rohan', 'Anika', 'Aditi',
    'Dev', 'Anushka', 'Shiv', 'Tanvi', 'Meera',
    'Radhika', 'Kabir', 'Ava', 'Nia', 'Yash',
    'Pooja', 'Sneha', 'Neha', 'Ritika', 'Siddharth',
    'Tara', 'Karan', 'Ritika', 'Aryan', 'Anvi',
    'Shreya', 'Mohan', 'Rahul', 'Sonia', 'Aishwarya',
    'Kavya', 'Aarushi', 'Rani', 'Rohit', 'Pankaj'
]

# Generating random marks for 5 subjects
marks = np.random.randint(0, 101, size=(50, 5))

# Defining subject names
subjects = ['Math', 'Physics', 'Chemistry', 'Biology', 'English']

# Creating the DataFrame
df = pd.DataFrame(marks, columns=subjects)
df['Name'] = student_names  # Adding the names
df['Total'] = df[subjects].sum(axis=1)  # Calculate the total marks

# Determining pass/fail based on the average marks
df['Result'] = np.where(df['Total'] / 5 >= 40, 'Pass', 'Fail')

# Reordering columns to ensure 'Name' is the first column
df = df[['Name'] + subjects + ['Total', 'Result']]

print(df)

         Name  Math  Physics  Chemistry  Biology  English  Total Result
0       Aarav    51       92         14       71       60    288   Pass
1      Vivaan    20       82         86       74       74    336   Pass
2      Aditya    87       99         23        2       21    232   Pass
3      Vihaan    52        1         87       29       37    206   Pass
4       Arjun     1       63         59       20       32    175   Fail
5         Sai    75       57         21       88       48    289   Pass
6     Reyansh    90       58         41       91       59    339   Pass
7       Ayaan    79       14         61       61       46    261   Pass
8       Anaya    61       50         54       63        2    230   Pass
9       Naira   100       50          6       20       72    248   Pass
10     Saanvi    38       17          3       88       59    205   Pass
11     Ishaan    13        8         89       52        1    163   Fail
12       Riya    83       91         59       70       43    346   Pass
13      Kaira     7       46         34       77       80    244   Pass
14    Krishna    35       49          3        1        5     93   Fail
15      Dhruv    53        3         53       92       62    263   Pass
16    Lakshmi    17       89         43       33       73    255   Pass
17      Rohan    61       99         13       94       47    314   Pass
18      Anika    14       71         77       86       61    309   Pass
19      Aditi    39       84         79       81       52    335   Pass
20        Dev    23       25         88       59       40    235   Pass
21    Anushka    28       14         44       64       88    238   Pass
22       Shiv    70        8         87        0        7    172   Fail
23      Tanvi    87       62         10       80        7    246   Pass
24      Meera    34       34         32        4       40    144   Fail
25    Radhika    27        6         72       71       11    187   Fail
26      Kabir    33       32         47       22       61    195   Fail
27        Ava    87       36         98       43       85    349   Pass
28        Nia    90       34         64       98      100    386   Pass
29       Yash    46       77          2        0        4    129   Fail
30      Pooja    89       13         26        8       78    214   Pass
31      Sneha    14       89         41       76       50    270   Pass
32       Neha    62       95         51       95        3    306   Pass
33     Ritika    93      100         22       14       42    271   Pass
34  Siddharth    28       35         12       31       70    176   Fail
35       Tara    58       85         27       65       41    276   Pass
36      Karan    44       61         56        5       27    193   Fail
37     Ritika    27       43         83       29       61    243   Pass
38      Aryan    74       91         88       61       96    410   Pass
39       Anvi     0       26         61       76        2    165   Fail
40     Shreya    69       71         26        8       61    235   Pass
41      Mohan    36       96         50       43       23    248   Pass
42      Rahul    78       58         31       95       87    349   Pass
43      Sonia    51       61         57       51       11    231   Pass
44  Aishwarya    38        1          2      100       55    196   Fail
45      Kavya    80       58          1        1       91    231   Pass
46    Aarushi    53       86        100       95       96    430   Pass
47       Rani     0       18          1       52       43    114   Fail
48      Rohit    89       31         69       31       67    287   Pass
49     Pankaj    54       74         55       16       37    236   Pass

In [3]:
# sort the data frame in accending order with respect to the total marks
df.sort_values(by='Total')

         Name  Math  Physics  Chemistry  Biology  English  Total Result
14    Krishna    35       49          3        1        5     93   Fail
47       Rani     0       18          1       52       43    114   Fail
29       Yash    46       77          2        0        4    129   Fail
24      Meera    34       34         32        4       40    144   Fail
11     Ishaan    13        8         89       52        1    163   Fail
39       Anvi     0       26         61       76        2    165   Fail
22       Shiv    70        8         87        0        7    172   Fail
4       Arjun     1       63         59       20       32    175   Fail
34  Siddharth    28       35         12       31       70    176   Fail
25    Radhika    27        6         72       71       11    187   Fail
36      Karan    44       61         56        5       27    193   Fail
26      Kabir    33       32         47       22       61    195   Fail
44  Aishwarya    38        1          2      100       55    196   Fail
10     Saanvi    38       17          3       88       59    205   Pass
3      Vihaan    52        1         87       29       37    206   Pass
30      Pooja    89       13         26        8       78    214   Pass
8       Anaya    61       50         54       63        2    230   Pass
43      Sonia    51       61         57       51       11    231   Pass
45      Kavya    80       58          1        1       91    231   Pass
2      Aditya    87       99         23        2       21    232   Pass
40     Shreya    69       71         26        8       61    235   Pass
20        Dev    23       25         88       59       40    235   Pass
49     Pankaj    54       74         55       16       37    236   Pass
21    Anushka    28       14         44       64       88    238   Pass
37     Ritika    27       43         83       29       61    243   Pass
13      Kaira     7       46         34       77       80    244   Pass
23      Tanvi    87       62         10       80        7    246   Pass
41      Mohan    36       96         50       43       23    248   Pass
9       Naira   100       50          6       20       72    248   Pass
16    Lakshmi    17       89         43       33       73    255   Pass
7       Ayaan    79       14         61       61       46    261   Pass
15      Dhruv    53        3         53       92       62    263   Pass
31      Sneha    14       89         41       76       50    270   Pass
33     Ritika    93      100         22       14       42    271   Pass
35       Tara    58       85         27       65       41    276   Pass
48      Rohit    89       31         69       31       67    287   Pass
0       Aarav    51       92         14       71       60    288   Pass
5         Sai    75       57         21       88       48    289   Pass
32       Neha    62       95         51       95        3    306   Pass
18      Anika    14       71         77       86       61    309   Pass
17      Rohan    61       99         13       94       47    314   Pass
19      Aditi    39       84         79       81       52    335   Pass
1      Vivaan    20       82         86       74       74    336   Pass
6     Reyansh    90       58         41       91       59    339   Pass
12       Riya    83       91         59       70       43    346   Pass
27        Ava    87       36         98       43       85    349   Pass
42      Rahul    78       58         31       95       87    349   Pass
28        Nia    90       34         64       98      100    386   Pass
38      Aryan    74       91         88       61       96    410   Pass
46    Aarushi    53       86        100       95       96    430   Pass

In [4]:
# sort the data frame in descending  order with respect to the total marks means the student with maximun marks  will be first in the data frame
df.sort_values(by='Total', ascending=False)

         Name  Math  Physics  Chemistry  Biology  English  Total Result
46    Aarushi    53       86        100       95       96    430   Pass
38      Aryan    74       91         88       61       96    410   Pass
28        Nia    90       34         64       98      100    386   Pass
27        Ava    87       36         98       43       85    349   Pass
42      Rahul    78       58         31       95       87    349   Pass
12       Riya    83       91         59       70       43    346   Pass
6     Reyansh    90       58         41       91       59    339   Pass
1      Vivaan    20       82         86       74       74    336   Pass
19      Aditi    39       84         79       81       52    335   Pass
17      Rohan    61       99         13       94       47    314   Pass
18      Anika    14       71         77       86       61    309   Pass
32       Neha    62       95         51       95        3    306   Pass
5         Sai    75       57         21       88       48    289   Pass
0       Aarav    51       92         14       71       60    288   Pass
48      Rohit    89       31         69       31       67    287   Pass
35       Tara    58       85         27       65       41    276   Pass
33     Ritika    93      100         22       14       42    271   Pass
31      Sneha    14       89         41       76       50    270   Pass
15      Dhruv    53        3         53       92       62    263   Pass
7       Ayaan    79       14         61       61       46    261   Pass
16    Lakshmi    17       89         43       33       73    255   Pass
9       Naira   100       50          6       20       72    248   Pass
41      Mohan    36       96         50       43       23    248   Pass
23      Tanvi    87       62         10       80        7    246   Pass
13      Kaira     7       46         34       77       80    244   Pass
37     Ritika    27       43         83       29       61    243   Pass
21    Anushka    28       14         44       64       88    238   Pass
49     Pankaj    54       74         55       16       37    236   Pass
40     Shreya    69       71         26        8       61    235   Pass
20        Dev    23       25         88       59       40    235   Pass
2      Aditya    87       99         23        2       21    232   Pass
45      Kavya    80       58          1        1       91    231   Pass
43      Sonia    51       61         57       51       11    231   Pass
8       Anaya    61       50         54       63        2    230   Pass
30      Pooja    89       13         26        8       78    214   Pass
3      Vihaan    52        1         87       29       37    206   Pass
10     Saanvi    38       17          3       88       59    205   Pass
44  Aishwarya    38        1          2      100       55    196   Fail
26      Kabir    33       32         47       22       61    195   Fail
36      Karan    44       61         56        5       27    193   Fail
25    Radhika    27        6         72       71       11    187   Fail
34  Siddharth    28       35         12       31       70    176   Fail
4       Arjun     1       63         59       20       32    175   Fail
22       Shiv    70        8         87        0        7    172   Fail
39       Anvi     0       26         61       76        2    165   Fail
11     Ishaan    13        8         89       52        1    163   Fail
24      Meera    34       34         32        4       40    144   Fail
29       Yash    46       77          2        0        4    129   Fail
47       Rani     0       18          1       52       43    114   Fail
14    Krishna    35       49          3        1        5     93   Fail

In [5]:
#  show the data frame of onlly those students who's result is pass
df.loc[df['Result']=='Pass']

       Name  Math  Physics  Chemistry  Biology  English  Total Result
0     Aarav    51       92         14       71       60    288   Pass
1    Vivaan    20       82         86       74       74    336   Pass
2    Aditya    87       99         23        2       21    232   Pass
3    Vihaan    52        1         87       29       37    206   Pass
5       Sai    75       57         21       88       48    289   Pass
6   Reyansh    90       58         41       91       59    339   Pass
7     Ayaan    79       14         61       61       46    261   Pass
8     Anaya    61       50         54       63        2    230   Pass
9     Naira   100       50          6       20       72    248   Pass
10   Saanvi    38       17          3       88       59    205   Pass
12     Riya    83       91         59       70       43    346   Pass
13    Kaira     7       46         34       77       80    244   Pass
15    Dhruv    53        3         53       92       62    263   Pass
16  Lakshmi    17       89         43       33       73    255   Pass
17    Rohan    61       99         13       94       47    314   Pass
18    Anika    14       71         77       86       61    309   Pass
19    Aditi    39       84         79       81       52    335   Pass
20      Dev    23       25         88       59       40    235   Pass
21  Anushka    28       14         44       64       88    238   Pass
23    Tanvi    87       62         10       80        7    246   Pass
27      Ava    87       36         98       43       85    349   Pass
28      Nia    90       34         64       98      100    386   Pass
30    Pooja    89       13         26        8       78    214   Pass
31    Sneha    14       89         41       76       50    270   Pass
32     Neha    62       95         51       95        3    306   Pass
33   Ritika    93      100         22       14       42    271   Pass
35     Tara    58       85         27       65       41    276   Pass
37   Ritika    27       43         83       29       61    243   Pass
38    Aryan    74       91         88       61       96    410   Pass
40   Shreya    69       71         26        8       61    235   Pass
41    Mohan    36       96         50       43       23    248   Pass
42    Rahul    78       58         31       95       87    349   Pass
43    Sonia    51       61         57       51       11    231   Pass
45    Kavya    80       58          1        1       91    231   Pass
46  Aarushi    53       86        100       95       96    430   Pass
48    Rohit    89       31         69       31       67    287   Pass
49   Pankaj    54       74         55       16       37    236   Pass

In [6]:
#  show  only those students who's result is fail
df.loc[df['Result']=='Fail']

         Name  Math  Physics  Chemistry  Biology  English  Total Result
4       Arjun     1       63         59       20       32    175   Fail
11     Ishaan    13        8         89       52        1    163   Fail
14    Krishna    35       49          3        1        5     93   Fail
22       Shiv    70        8         87        0        7    172   Fail
24      Meera    34       34         32        4       40    144   Fail
25    Radhika    27        6         72       71       11    187   Fail
26      Kabir    33       32         47       22       61    195   Fail
29       Yash    46       77          2        0        4    129   Fail
34  Siddharth    28       35         12       31       70    176   Fail
36      Karan    44       61         56        5       27    193   Fail
39       Anvi     0       26         61       76        2    165   Fail
44  Aishwarya    38        1          2      100       55    196   Fail
47       Rani     0       18          1       52       43    114   Fail

In [7]:
# show the  toper of the batch
maximum_marks= df['Total'].max()
Topper=df.loc[(df['Total']==maximum_marks)]
Topper

       Name  Math  Physics  Chemistry  Biology  English  Total Result
46  Aarushi    53       86        100       95       96    430   Pass

In [8]:
# show the student with lowest marks in total
lowest_total= df['Total'].min()
df.loc[(df['Total']==lowest_total)]

       Name  Math  Physics  Chemistry  Biology  English  Total Result
14  Krishna    35       49          3        1        5     93   Fail

In [9]:
#  find the student who got maximum marks in English
Eng_max=df['English'].max()
df.loc[(df['English']==Eng_max)]

   Name  Math  Physics  Chemistry  Biology  English  Total Result
28  Nia    90       34         64       98      100    386   Pass

In [10]:
# show the list of students  who got more  then 80 marks in math and English both in ascending order
maths_eng=df.loc[(df['English']>=80)&(df['Math']>=80)]
maths_eng.sort_values(by='English', ascending=False)

     Name  Math  Physics  Chemistry  Biology  English  Total Result
28    Nia    90       34         64       98      100    386   Pass
45  Kavya    80       58          1        1       91    231   Pass
27    Ava    87       36         98       43       85    349   Pass

In [11]:
# Show the  student detail who got maximum marks in Biology
top_bio=df['Biology'].max()
df.loc[(df['Biology']==top_bio) ]

         Name  Math  Physics  Chemistry  Biology  English  Total Result
44  Aishwarya    38        1          2      100       55    196   Fail

In [12]:
# arrnage the rsult in decending order means the one who toped should be top in the data set as rank 1
topper_first=df.sort_values(by='Total', ascending=False)
topper_first.head()

       Name  Math  Physics  Chemistry  Biology  English  Total Result
46  Aarushi    53       86        100       95       96    430   Pass
38    Aryan    74       91         88       61       96    410   Pass
28      Nia    90       34         64       98      100    386   Pass
27      Ava    87       36         98       43       85    349   Pass
42    Rahul    78       58         31       95       87    349   Pass

In [13]:
# first 5 toppers
topper_first.head(5)

       Name  Math  Physics  Chemistry  Biology  English  Total Result
46  Aarushi    53       86        100       95       96    430   Pass
38    Aryan    74       91         88       61       96    410   Pass
28      Nia    90       34         64       98      100    386   Pass
27      Ava    87       36         98       43       85    349   Pass
42    Rahul    78       58         31       95       87    349   Pass

In [14]:
# last 5 rankers
topper_first.tail(5)

       Name  Math  Physics  Chemistry  Biology  English  Total Result
11   Ishaan    13        8         89       52        1    163   Fail
24    Meera    34       34         32        4       40    144   Fail
29     Yash    46       77          2        0        4    129   Fail
47     Rani     0       18          1       52       43    114   Fail
14  Krishna    35       49          3        1        5     93   Fail

In [15]:
newdf=df[['Name','Math','Total']]
newdf=newdf.sort_values(by='Total',ascending=True)
newdf.head()

       Name  Math  Total
14  Krishna    35     93
47     Rani     0    114
29     Yash    46    129
24    Meera    34    144
11   Ishaan    13    163

In [16]:
#  find the student that score maximum marks in the Maths
value=df['Math'].max()
df.loc[df['Math']==value]

    Name  Math  Physics  Chemistry  Biology  English  Total Result
9  Naira   100       50          6       20       72    248   Pass

In [17]:
value2=df['Total'].max()
df.loc[df['Total']==value2]

       Name  Math  Physics  Chemistry  Biology  English  Total Result
46  Aarushi    53       86        100       95       96    430   Pass

In [18]:
sort_axis=df.sort_index(axis=0, ascending=False)
sort_axis.head()

       Name  Math  Physics  Chemistry  Biology  English  Total Result
49   Pankaj    54       74         55       16       37    236   Pass
48    Rohit    89       31         69       31       67    287   Pass
47     Rani     0       18          1       52       43    114   Fail
46  Aarushi    53       86        100       95       96    430   Pass
45    Kavya    80       58          1        1       91    231   Pass

In [19]:
# how to delete the certain value as entire row , means we have to delete the entire column with a conditon
only_pass=df.drop(df[df['Result']!='Pass'].index)
only_pass.head()

     Name  Math  Physics  Chemistry  Biology  English  Total Result
0   Aarav    51       92         14       71       60    288   Pass
1  Vivaan    20       82         86       74       74    336   Pass
2  Aditya    87       99         23        2       21    232   Pass
3  Vihaan    52        1         87       29       37    206   Pass
5     Sai    75       57         21       88       48    289   Pass

In [20]:
# how to delete those row with certain index number and then by the condion
deleting=df.drop(1) # it will delete the first  row entire first row
deleting.head()

     Name  Math  Physics  Chemistry  Biology  English  Total Result
0   Aarav    51       92         14       71       60    288   Pass
2  Aditya    87       99         23        2       21    232   Pass
3  Vihaan    52        1         87       29       37    206   Pass
4   Arjun     1       63         59       20       32    175   Fail
5     Sai    75       57         21       88       48    289   Pass

In [21]:
# delelting the row with specific contion
del_with_condi=df.drop(df[df['Total']<300].index)
del_with_condi.head()

       Name  Math  Physics  Chemistry  Biology  English  Total Result
1    Vivaan    20       82         86       74       74    336   Pass
6   Reyansh    90       58         41       91       59    339   Pass
12     Riya    83       91         59       70       43    346   Pass
17    Rohan    61       99         13       94       47    314   Pass
18    Anika    14       71         77       86       61    309   Pass

In [22]:
# deleting the row with NaN vlaues from the data set
df.dropna(inplace=True)  # it will  remove all the NaN values from the data set
df.head()

     Name  Math  Physics  Chemistry  Biology  English  Total Result
0   Aarav    51       92         14       71       60    288   Pass
1  Vivaan    20       82         86       74       74    336   Pass
2  Aditya    87       99         23        2       21    232   Pass
3  Vihaan    52        1         87       29       37    206   Pass
4   Arjun     1       63         59       20       32    175   Fail

In [23]:
df.replace({'Aarav':'Aarav Singh'},inplace=True)
df.head()

          Name  Math  Physics  Chemistry  Biology  English  Total Result
0  Aarav Singh    51       92         14       71       60    288   Pass
1       Vivaan    20       82         86       74       74    336   Pass
2       Aditya    87       99         23        2       21    232   Pass
3       Vihaan    52        1         87       29       37    206   Pass
4        Arjun     1       63         59       20       32    175   Fail

In [24]:
# we have to find the data of those students whos total marks is greater then 400
#  and  V V I
# add a new row with marks of each subject
df1=df.loc[df['Total']>400]
df1.loc[len(df1)] = ['RAM SINGH', 2, 2, 2, 2, 2, 10, 'Pass']
df1.loc[len(df1)]=['Shyam',4,5,4,2,5,6,'Fail']
df1

<ipython-input-24-6bec25395e68>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[len(df1)] = ['RAM SINGH', 2, 2, 2, 2, 2, 10, 'Pass']
<ipython-input-24-6bec25395e68>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[len(df1)]=['Shyam',4,5,4,2,5,6,'Fail']

         Name  Math  Physics  Chemistry  Biology  English  Total Result
38      Aryan    74       91         88       61       96    410   Pass
46    Aarushi    53       86        100       95       96    430   Pass
2   RAM SINGH     2        2          2        2        2     10   Pass
3       Shyam     4        5          4        2        5      6   Fail

In [25]:
#  creating new data set with duplicate values
#then we will remove the duplicate values and do some operation in which
#keep first , keep last these are the options
import pandas as pd

import pandas as pd

# Sample data with duplicate rows
data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Amit', 'Sara', 'Rahul', 'Priya'],
    'Math': [85, 92, 78, 85, 76, 92, 78],
    'Physics': [88, 79, 85, 88, 88, 78, 86],
    'Chemistry': [90, 76, 89, 90, 77, 76, 89],
    'Biology': [78, 80, 85, 78, 81, 80, 85],
    'English': [84, 90, 88, 84, 83, 90, 88],
    'Total': [425, 417, 425, 425, 399, 417, 425],
    'Result': ['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass']
}

dupli = pd.DataFrame(data)

print(dupli)

    Name  Math  Physics  Chemistry  Biology  English  Total Result
0   Amit    85       88         90       78       84    425   Pass
1  Rahul    92       79         76       80       90    417   Pass
2  Priya    78       85         89       85       88    425   Pass
3   Amit    85       88         90       78       84    425   Pass
4   Sara    76       88         77       81       83    399   Pass
5  Rahul    92       78         76       80       90    417   Pass
6  Priya    78       86         89       85       88    425   Pass

In [26]:

# dupli = dupli.drop_duplicates()

# Drop duplicate rows based only on the 'Name' column, keeping the last occurrence
dupli = dupli.drop_duplicates(subset=['Name'], keep='last')

print(dupli)

    Name  Math  Physics  Chemistry  Biology  English  Total Result
3   Amit    85       88         90       78       84    425   Pass
4   Sara    76       88         77       81       83    399   Pass
5  Rahul    92       78         76       80       90    417   Pass
6  Priya    78       86         89       85       88    425   Pass

In [27]:
import pandas as pd

import pandas as pd

# Sample data with duplicate rows
data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Amit', 'Sara', 'Rahul', 'Priya'],
    'Math': [85, 92, 78, 85, 76, 92, 78],
    'Physics': [88, 79, 85, 88, 88, 78, 86],
    'Chemistry': [90, 76, 89, 90, 77, 76, 89],
    'Biology': [78, 80, 85, 78, 81, 80, 85],
    'English': [84, 90, 88, 84, 83, 90, 88],
    'Total': [425, 417, 425, 425, 399, 417, 425],
    'Result': ['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass']
}

dupli2 = pd.DataFrame(data)

print(dupli2)

    Name  Math  Physics  Chemistry  Biology  English  Total Result
0   Amit    85       88         90       78       84    425   Pass
1  Rahul    92       79         76       80       90    417   Pass
2  Priya    78       85         89       85       88    425   Pass
3   Amit    85       88         90       78       84    425   Pass
4   Sara    76       88         77       81       83    399   Pass
5  Rahul    92       78         76       80       90    417   Pass
6  Priya    78       86         89       85       88    425   Pass

In [28]:
#  V V I in this we are going to find the duplicate and delete all the value related to it. means
# we have to remove the duplicate as well as the single vlaue related to it
dupli2=dupli2.drop_duplicates(subset=['Name'], keep=False)
dupli2

   Name  Math  Physics  Chemistry  Biology  English  Total Result
4  Sara    76       88         77       81       83    399   Pass

In [29]:
import pandas as pd
import pandas as pd

# Sample data with duplicate rows
data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Amit', 'Sara', 'Rahul', 'Priya'],
    'Math': [85, 92, 78, 85, 76, 92, 78],
    'Physics': [88, 79, 85, 88, 88, 78, 86],
    'Chemistry': [90, 76, 89, 90, 77, 76, 89],
    'Biology': [78, 80, 85, 78, 81, 80, 85],
    'English': [84, 90, 88, 84, 83, 90, 88],
    'Total': [425, 417, 425, 425, 399, 417, 425],
    'Result': ['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass']
}
dupli3 = pd.DataFrame(data)
dupli3['Name'].value_counts()

Name
Amit     2
Rahul    2
Priya    2
Sara     1
Name: count, dtype: int64

In [35]:
#  lets work with the excel file as i have done all the operations of csv file but now its time to work with the excel file
# i do have the file of excel as named Excel
Exce=pd.read_excel('Excel.xlsx')
Exce

           Name  CGPA Language  Pincode
0     Ram Kumar   9.5      C++   801103
1  Shita Kumari   9.2     Java   801157
2      Lakshman   8.5   Python   800002
3       Hanuman   8.8      C++   852013

In [34]:
# The excel file  contians two excel sheet in it if we dont pass the argumnet as sheet_name it will take
# sheet1 by default but if we have to view a specifc sheet then we have to pass the sheet_name as atribute
# reading Sheet 2 in this code

sheet2=pd.read_excel('Excel.xlsx', sheet_name='Sheet2')
sheet2

      Name  CGPA Language  Pincode
0    Radha  10.0      C++   801103
1    Shyam   8.8     Java   801157
2     Mira   7.2   Python   800002
3  Shubham   9.3      C++   852013